### ISSUE TITLE
Forwarding an album

### ISSUE THREAD

**Issue by GauthamramRavichandran** [ukinti/garnet#13]
In telethon, there is an `events.Album` to get the album, recently implemented.
I need to forward this album without breaking captions or into multiple messages. How can I do this?

**Comment by uwinx** [comment]
`garnet.events.Album` is just a patched version of `telethon.events.Album`, not sure what could possible break. can you show traceback and code to reproduce?

**Comment by GauthamramRavichandran** [comment]
There is nothing breaking, so basically no traceback/exceptions. It's just that it is not working as expected.

I'll share what I experienced, I have sent an album with two photos in a channel. But in updates, I'm receiving this one album as two separate mesages. My goal is to forward this album to another channel, and when I do that, it's landing as two separate images instead of one album

**Comment by uwinx** [comment]
Is it working in telethon?

**Comment by GauthamramRavichandran** [comment]
I don't have the code sample, but I did tried in telethon. It worked as expected (2 images in one post with captions as well).

**Comment by uwinx** [comment]
Well, telethon depends on telethon. Install the newest telethon with garnet

**Comment by uwinx** [comment]
@GauthamramRavichandran, how did it go, can we close this one for now?

**Comment by uwinx** [comment]
@GauthamramRavichandran ping :ping_pong:

**Comment by GauthamramRavichandran** [comment]
Sorry, couldn't check on this for a few days. This is the version I'm using (I even pulled out the latest master branch of telethon)
```
telegram-garnet==0.3.0
Telethon==1.14.0
```
I just tested now on garnet, send an album with two photos in a channel => bot is to forward the album but it forwarded as two separate photos
But in plain telethon, I tested which forwarded as an album

**Comment by uwinx** [comment]
@GauthamramRavichandran, can you reproduce it with new garnet?
