### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by cyphunk** [ukinti/garnet#20]
When running on ipv6 hosts get following error. Could you direct to where the underlying client  option 'use_ipv6' could be set?

```
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
```

**Comment by uwinx** [comment]
Hey, @cyphunk! That can be done easily by passing a real instance of `garnet.TelegramClient` to `garnet.runner.run` as `bot` parameter.
you can see the [definition](https://github.com/ukinti/garnet/blob/56bec78e54714e009e2052f2162e2a7eea0156f9/src/_garnet/runner.py#L38)

you can also `start` your `TelegramClient` before you pass it run in order to customize an "early runtime".

**Comment by cyphunk** [comment]
Hi, I switched to IPV4. I had tried to copy+paste the Definition you mentioned but was having errors. (tried this was before I filed this issue). Specifically I tried:

```
from _garnet.client import TelegramClient
bot = TelegramClient(
            session=my_session_dsn,
            api_id=int(my_app_id),
            api_hash=my_app_hash,        
)
from garnet.runner import run, launch
launch("botname", run(router, JSONStorage('states.json'), bot))
```

If you see something obviously wrong there I would be happy to know. If not, then perhaps there was a different issue which I cant test now because I was in a rush so switched to an ipv4 server instead.

thank you for your input though

**Comment by uwinx** [comment]
Glad that was helpful, closing this now.

Thanks for pointing out your solution to the problem.

**Comment by cyphunk** [comment]
Not sure why but the boilerplate example I gave will not work. When I let garnet create the bot instance it works. When I create it as shown it fails. (and I fixed a minor error from before)
