### ISSUE TITLE
How to access client instance to send messages outside Router

### ISSUE THREAD

**Issue by cyphunk** [ukinti/garnet#21]
What would the recommended method be to send_message from a worker thread. I'd like a management thread to routinely check the status of things and then send a message. I assumed I would need to instantiate a TelegramClient on my own but despite many attempts to replicate that portion of the run/launcher code (see https://github.com/ukinti/garnet/issues/20) it fails to setup a TelegramClient that works.

**Comment by uwinx** [comment]
@cyphunk, that was actually the right way to access it. Please provide minimal reproducible code to get an error.

**Comment by uwinx** [comment]
@cyphunk, did you resolve this?

**Comment by cyphunk** [comment]
I switched from garnet and used telethon directly. I am sure I will have a chance to explore the issue again the future. But I'll close this. Thank you for checking on me again <3
