### ISSUE TITLE
Exception from the example(FSM) I tried

### ISSUE THREAD

**Issue by GauthamramRavichandran** [ukinti/garnet#9]
```
Task exception was never retrieved
future: <Task finished coro=<TelegramClient._dispatch_update() done, defined at xxxxx/lib/python3.7/site-packages/garnet/client.py:211> exception=TypeError("'in <string>' requires string as left operand, not NoneType")>
Traceback (most recent call last):
  File "xxxxx/lib/python3.7/site-packages/garnet/client.py", line 270, in _dispatch_update
    if (await filter_.function(event, context)) is False:
  File "xxx/lib/python3.7/site-packages/garnet/filters/state.py", line 39, in _f
    return (await context.get_state()) in _s
TypeError: 'in <string>' requires string as left operand, not NoneType
```
Steps to reproduce,
1. Run the bot
2. Send some random text (not /start) [First time it's not throwing any error]
3. Send some more random text [This time, this will throw an exception like above]

I have a doubt, how can we choose where the states should be stored? (db/file/memory)

**Comment by uwinx** [comment]
state of the user is stored with all data user has.

Could you provide a code to reproduce?

**Comment by uwinx** [comment]
@GauthamramRavichandran, thanks for the report. Error happens when your user's state is `None`

**Comment by GauthamramRavichandran** [comment]
> I have a doubt, how can we choose where the states should be stored? (db/file/memory)

Is there any example of it? I am trying to store a client (`TelegramClient`) inside the `context` and I'm getting pickle error.

**Comment by uwinx** [comment]
You should never do that. Don't store complex pythonic objects.

**Comment by GauthamramRavichandran** [comment]
I learned it now :)
You still haven't cleared my doubt regarding choice of `BaseStorage`?

**Comment by uwinx** [comment]
I'd use redis storage for almost everything.

**Comment by uwinx** [comment]
What do you mean? I think, it's clear that data to store must json-serializable.
